const nodemailer = require('nodemailer');
const path = require('path');
const sgMail = require('@sendgrid/mail');
const config = require('../config/key');
sgMail.setApiKey(config.sendgridAPIKey);

//const transport = nodemailer.createTransport({
//  service: 'Mailgun',
//  auth: {
//    user: config.MAILGUN_USER,
//    pass: config.MAILGUN_PASS
//  },
//  tls: {
//    rejectUnauthorized: false
//  }
//});

//ye personel ha mera
const transport = nodemailer.createTransport({
    host: "smtp.mailtrap.io",
    port: 2525,
    auth: {
      user: "1034e6ad06db60", //generated by Mailtrap
      pass: "dbf98932cff680" //generated by Mailtrap
    }
  });

module.exports = {
  sendEmail(from, to, subject, html) {
    console.log('From: ' + from);
    console.log('To: ' + to);
    return new Promise((resolve, reject) => {

      const msg = {
        to,
        // from: 'faizan@livewireapps.com',

        from: 'bilal@livewirelabs.co',
        subject,
        // text: 'and easy to do anywhere, even with Node.js',
        html,
      };
      sgMail.send(msg).then(info => {
        console.log(info);
        console.log(info.body);
        resolve(info);
      }).catch(error => {
          console.log(error);
          console.log(error.response.body);
      });
      // transport.sendMail({ from, subject, to, html }, (err, info) => {
      //   if (err) {reject(err);
      //     console.log(err)
      //   }
      //   console.log(info);
        
      // });
    });
  }
}